version: "3.9"

services:
  # Our NestJS Api
  api:
    image: francescoxx/nestapp:1.0.0
    build: .
    restart: always
    volumes:
      - .:/app
      - /app/node_modules/
    depends_on: 
      - postgres
    environment:
      DATABASE_URL: postgres://postgres:niharika@postgres:5432/chatApp
      JWT_SECRET: hard_to_guess_secret_123
      PORT: 3000
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: niharika
      POSTGRES_DB: chatApp
    ports:
      - 3000:3000

  # Our Postgres Database for NestJS to connect to
  postgres:
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: niharika
      POSTGRES_DB: chatApp
    volumes:
      - pgdata:/var/lib/postgresql/data
    image: postgres:12
    ports:
      - 5432:5432

volumes:
  pgdata: {}